<?php

declare(strict_types=1);

namespace Xterr\UBL\Generator\Tests\Unit\Emitter;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Xterr\UBL\Generator\Config\GeneratorConfig;
use Xterr\UBL\Generator\Emitter\EnumEmitter;
use Xterr\UBL\Generator\Emitter\FileWriter;
use Xterr\UBL\Generator\Emitter\RegistryEmitter;

final class EnumRegistryEmitterTest extends TestCase
{
    private GeneratorConfig $config;

    protected function setUp(): void
    {
        $this->config = GeneratorConfig::defaults();
    }

    #[Test]
    public function enumEmitterProducesBackedStringEnumWithCases(): void
    {
        $emitter = new EnumEmitter($this->config);
        $output = $emitter->emit('DocumentStatusCode', ['QUESTION', 'REQUIREMENT', '380']);

        self::assertStringContainsString('declare(strict_types=1);', $output);
        self::assertStringContainsString('namespace Xterr\\UBL\\Enum;', $output);
        self::assertStringContainsString('enum DocumentStatusCode: string', $output);
        self::assertStringContainsString("case QUESTION = 'QUESTION';", $output);
        self::assertStringContainsString("case REQUIREMENT = 'REQUIREMENT';", $output);
        self::assertStringContainsString("case VALUE_380 = '380';", $output);
        self::assertStringContainsString('@generated by php-ubl code generator', $output);
    }

    #[Test]
    public function enumEmitterIncludesDocumentationWhenEnabled(): void
    {
        $emitter = new EnumEmitter($this->config);
        $output = $emitter->emit('CurrencyCode', ['EUR', 'USD'], 'ISO 4217 currency codes');

        self::assertStringContainsString('ISO 4217 currency codes', $output);
    }

    #[Test]
    public function enumEmitterOmitsDocumentationWhenDisabled(): void
    {
        $config = $this->config->withOverrides(['include_documentation' => false]);
        $emitter = new EnumEmitter($config);
        $output = $emitter->emit('CurrencyCode', ['EUR', 'USD'], 'ISO 4217 currency codes');

        self::assertStringNotContainsString('ISO 4217 currency codes', $output);
    }

    #[Test]
    public function enumEmitterOmitsGeneratedTagWhenDisabled(): void
    {
        $config = $this->config->withOverrides(['include_generated_tag' => false]);
        $emitter = new EnumEmitter($config);
        $output = $emitter->emit('CurrencyCode', ['EUR']);

        self::assertStringNotContainsString('@generated', $output);
    }

    #[Test]
    public function registryEmitterProducesDocumentRegistryWithMapAndMethods(): void
    {
        $emitter = new RegistryEmitter($this->config);
        $output = $emitter->emitDocumentRegistry([
            'Xterr\\UBL\\Doc\\Invoice' => [
                'namespace' => 'urn:oasis:names:specification:ubl:schema:xsd:Invoice-2',
                'localName' => 'Invoice',
            ],
        ]);

        self::assertStringContainsString('declare(strict_types=1);', $output);
        self::assertStringContainsString('namespace Xterr\\UBL\\Xml;', $output);
        self::assertStringContainsString('final class DocumentRegistry', $output);
        self::assertStringContainsString('private const MAP', $output);
        self::assertStringContainsString("'Xterr\\UBL\\Doc\\Invoice'", $output);
        self::assertStringContainsString('public static function classFor(string $namespace, string $localName): ?string', $output);
        self::assertStringContainsString('public static function rootElementFor(string $className): ?array', $output);
        self::assertStringContainsString('@generated by php-ubl code generator', $output);
    }

    #[Test]
    public function registryEmitterProducesTypeMapWithMapAndMethod(): void
    {
        $emitter = new RegistryEmitter($this->config);
        $output = $emitter->emitTypeMap([
            'TaxAmount' => 'Xterr\\UBL\\Cbc\\Amount',
            'LineExtensionAmount' => 'Xterr\\UBL\\Cbc\\Amount',
        ]);

        self::assertStringContainsString('declare(strict_types=1);', $output);
        self::assertStringContainsString('namespace Xterr\\UBL\\Xml;', $output);
        self::assertStringContainsString('final class TypeMap', $output);
        self::assertStringContainsString('private const MAP', $output);
        self::assertStringContainsString("'TaxAmount'", $output);
        self::assertStringContainsString("'Xterr\\UBL\\Cbc\\Amount'", $output);
        self::assertStringContainsString('public static function classFor(string $cbcElementName): ?string', $output);
    }

    #[Test]
    public function fileWriterWritesFileToOutputDir(): void
    {
        $tmpDir = sys_get_temp_dir() . '/php-ubl-test-' . uniqid();

        try {
            $writer = new FileWriter($tmpDir);
            $writer->write('Enum/CurrencyCode.php', '<?php // test content');

            $expectedPath = $tmpDir . '/Enum/CurrencyCode.php';
            self::assertFileExists($expectedPath);
            self::assertSame('<?php // test content', file_get_contents($expectedPath));
            self::assertSame($tmpDir, $writer->getOutputDir());
        } finally {
            if (is_dir($tmpDir)) {
                $this->removeDirectory($tmpDir);
            }
        }
    }

    private function removeDirectory(string $dir): void
    {
        $items = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \RecursiveDirectoryIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST,
        );

        foreach ($items as $item) {
            if ($item->isDir()) {
                rmdir($item->getPathname());
            } else {
                unlink($item->getPathname());
            }
        }

        rmdir($dir);
    }
}
