<?php declare(strict_types=1);

namespace Xterr\UBL\Generator\Emitter;

use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PsrPrinter;
use Xterr\UBL\Generator\Codelist\ParsedCodelist;
use Xterr\UBL\Generator\Config\GeneratorConfig;
use Xterr\UBL\Xml\Mapping\CodelistMeta;

final class CodelistEnumEmitter
{
    public function __construct(
        private readonly GeneratorConfig $config,
    ) {}

    public function emit(string $enumName, ParsedCodelist $codelist): string
    {
        $file = new PhpFile();
        $file->setStrictTypes();

        $ns = $file->addNamespace($this->config->namespace . '\\' . $this->config->codelistNamespace);
        $ns->addUse(CodelistMeta::class);

        $enum = $ns->addEnum($enumName);
        $enum->setType('string');

        if ($this->config->includeGeneratedTag) {
            $enum->addComment('@generated by php-ubl code generator — do not edit');
        }

        // #[CodelistMeta(...)] attribute
        $metaArgs = ['listID' => $codelist->listID];
        if ($codelist->agencyID !== null) {
            $metaArgs['listAgencyID'] = $codelist->agencyID;
        }
        if ($codelist->version !== null) {
            $metaArgs['listVersionID'] = $codelist->version;
        }
        $enum->addAttribute(CodelistMeta::class, $metaArgs);

        foreach ($codelist->entries as $entry) {
            if (strtoupper($entry->status) !== 'ACTIVE') {
                continue;
            }

            $caseName = $this->toCaseName($entry->code);

            if ($this->config->includeDocumentation && $entry->name !== null) {
                // Nette doesn't support per-case comments directly on EnumCase,
                // so we skip inline docs for now — the case name + value is self-documenting.
            }

            $enum->addCase($caseName, $entry->code);
        }

        $printer = new PsrPrinter();

        return $printer->printFile($file);
    }

    private function toCaseName(string $value): string
    {
        $name = preg_replace('/[^a-zA-Z0-9]/', '_', $value);
        $name = strtoupper($name);

        if (ctype_digit($name[0] ?? '')) {
            $name = 'VALUE_' . $name;
        }

        $name = preg_replace('/_+/', '_', $name);

        return rtrim($name, '_');
    }
}
