<?php

declare(strict_types=1);

namespace Xterr\UBL\Generator\Emitter;

use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PsrPrinter;
use Xterr\UBL\Generator\Config\GeneratorConfig;

final class EnumEmitter
{
    public function __construct(
        private readonly GeneratorConfig $config,
    ) {
    }

    /**
     * @param list<string> $values Enumeration values from XSD
     */
    public function emit(string $enumName, array $values, ?string $documentation = null): string
    {
        $file = new PhpFile();
        $file->setStrictTypes();

        $ns = $file->addNamespace($this->config->namespace . '\\' . $this->config->enumNamespace);
        $enum = $ns->addEnum($enumName);
        $enum->setType('string');

        if ($this->config->includeGeneratedTag) {
            $enum->addComment('@generated by php-ubl code generator — do not edit');
        }
        if ($documentation !== null && $this->config->includeDocumentation) {
            $enum->addComment('');
            $enum->addComment($documentation);
        }

        foreach ($values as $value) {
            $caseName = $this->toCaseName($value);
            $enum->addCase($caseName, $value);
        }

        $printer = new PsrPrinter();

        return $printer->printFile($file);
    }

    private function toCaseName(string $value): string
    {
        $name = preg_replace('/[^a-zA-Z0-9]/', '_', $value);
        $name = strtoupper($name);

        if (ctype_digit($name[0] ?? '')) {
            $name = 'VALUE_' . $name;
        }

        $name = preg_replace('/_+/', '_', $name);

        return rtrim($name, '_');
    }
}
