<?php

declare(strict_types=1);

namespace Xterr\UBL\Generator\Emitter;

use Nette\PhpGenerator\Literal;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PsrPrinter;
use Xterr\UBL\Generator\Config\GeneratorConfig;

final class RegistryEmitter
{
    public function __construct(
        private readonly GeneratorConfig $config,
    ) {
    }

    /**
     * @param array<string, array{namespace: string, localName: string}> $documentRoots
     *   Keys are PHP FQCNs, values are XML root element info
     */
    public function emitDocumentRegistry(array $documentRoots): string
    {
        $file = new PhpFile();
        $file->setStrictTypes();

        $ns = $file->addNamespace($this->config->namespace . '\\Xml');
        $class = $ns->addClass('DocumentRegistry');
        $class->setFinal();

        if ($this->config->includeGeneratedTag) {
            $class->addComment('@generated by php-ubl code generator — do not edit');
        }

        $map = [];
        foreach ($documentRoots as $fqcn => $info) {
            $key = '{' . $info['namespace'] . '}' . $info['localName'];
            $map[$key] = $fqcn;
        }

        $class->addConstant('MAP', $map)->setPrivate();

        $method = $class->addMethod('classFor')
            ->setStatic()
            ->setReturnType('string')
            ->setReturnNullable();
        $method->addParameter('namespace')->setType('string');
        $method->addParameter('localName')->setType('string');
        $method->setBody("return self::MAP['{' . \$namespace . '}' . \$localName] ?? null;");

        $method2 = $class->addMethod('rootElementFor')
            ->setStatic()
            ->setReturnType('array')
            ->setReturnNullable();
        $method2->addComment('@param class-string $className');
        $method2->addComment('@return array{namespace: string, localName: string}|null');
        $method2->addParameter('className')->setType('string');
        $method2->setBody(<<<'PHP'
            foreach (self::MAP as $key => $class) {
                if ($class === $className) {
                    preg_match('/^\{(.+?)\}(.+)$/', $key, $m);
                    return ['namespace' => $m[1], 'localName' => $m[2]];
                }
            }
            return null;
            PHP);

        $printer = new PsrPrinter();

        return $printer->printFile($file);
    }

    /**
     * @param array<string, string> $elementToClass element name → leaf class FQCN
     */
    public function emitClassMap(array $elementToClass): string
    {
        $file = new PhpFile();
        $file->setStrictTypes();

        $ns = $file->addNamespace($this->config->namespace . '\\Xml');

        // Collect unique FQCNs and add use imports
        $uniqueClasses = array_unique(array_values($elementToClass));
        sort($uniqueClasses);
        foreach ($uniqueClasses as $fqcn) {
            $ns->addUse($fqcn);
        }

        $class = $ns->addClass('ClassMap');
        $class->setFinal();

        if ($this->config->includeGeneratedTag) {
            $class->addComment('@generated by php-ubl code generator — do not edit');
        }

        // Build MAP with ::class references instead of plain strings
        $mapWithClassRefs = [];
        foreach ($elementToClass as $elementName => $fqcn) {
            $shortName = $this->shortClassName($fqcn);
            $mapWithClassRefs[$elementName] = new Literal($shortName . '::class');
        }

        $class->addConstant('MAP', $mapWithClassRefs)->setPrivate();

        $method = $class->addMethod('classFor')
            ->setStatic()
            ->setReturnType('string')
            ->setReturnNullable();
        $method->addParameter('elementName')->setType('string');
        $method->addComment('@param string $elementName XML element local name (e.g. "TaxAmount", "ExtensionAgencyID")');
        $method->addComment('@return class-string|null The PHP leaf class for this element, or null if unknown');
        $method->setBody('return self::MAP[$elementName] ?? null;');

        $printer = new PsrPrinter();

        return $printer->printFile($file);
    }

    private function shortClassName(string $fqcn): string
    {
        $parts = explode('\\', $fqcn);

        return end($parts);
    }
}
